version: '3.8'

services:
  api:
    build: .
    image: leadership-chatbot-api
    container_name: leadership-chatbot-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./instance:/app/instance
      - ./tests:/app/tests
      - db_data:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:1.25-alpine
    container_name: leadership-chatbot-nginx
    restart: unless-stopped
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - api

volumes:
  db_data: 